# Generated by Django 2.2.5 on 2019-10-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag', models.URLField()),
            ],
            options={
                'verbose_name': 'nation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=200)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='towns', to='neigh1.Nation')),
            ],
            options={
                'verbose_name': 'town',
                'ordering': ['nation'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('occupants', models.IntegerField()),
                ('registered_occupants', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='neigh1.Town')),
            ],
            options={
                'verbose_name': 'neighborhood',
                'ordering': ['name'],
            },
        ),
    ]
