# Generated by Django 2.2.5 on 2019-10-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='location',
        ),
        migrations.RemoveField(
            model_name='town',
            name='nation',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
