# Generated by Django 2.2.5 on 2019-10-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0005_auto_20191025_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
