# Generated by Django 2.2.5 on 2019-10-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
