# Generated by Django 2.2.5 on 2019-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
