# Generated by Django 2.2.5 on 2019-10-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0010_auto_20191027_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
