# Generated by Django 2.2.5 on 2019-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0012_auto_20191027_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='calling_codes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
