# Generated by Django 2.2.5 on 2019-10-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0013_auto_20191027_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='neigh1.Neighborhood'),
        ),
    ]
