# Generated by Django 2.2.5 on 2019-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0016_auto_20191027_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='bussiness_photo',
            field=models.ImageField(default='bussiness_pics/no-photo.jpg', upload_to='bussiness_pics/'),
        ),
    ]
