# Generated by Django 2.2.5 on 2019-10-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0017_bussines_bussiness_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bussineses',
        ),
        migrations.DeleteModel(
            name='Bussines',
        ),
    ]
