# Generated by Django 2.2.5 on 2019-10-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0018_auto_20191027_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bussines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=150)),
                ('bussiness_photo', models.ImageField(default='bussiness_pics/no-photo.jpg', upload_to='bussiness_pics/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bussines', to='neigh1.Profile')),
            ],
            options={
                'verbose_name': 'bussines',
                'ordering': ['name'],
            },
        ),
    ]
