# Generated by Django 2.2.5 on 2019-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0020_auto_20191027_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(null=True),
        ),
    ]
