# Generated by Django 2.2.6 on 2019-10-28 09:01

import ckeditor5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0021_profile_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor5.fields.RichTextField()),
            ],
        ),
    ]
