# Generated by Django 2.2.6 on 2019-10-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neigh1', '0022_neighborhoodpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhoodpost',
            options={'ordering': ['posted_on']},
        ),
        migrations.AddField(
            model_name='neighborhoodpost',
            name='image',
            field=models.ImageField(default='neigh_post/no-image.jpg', upload_to='neigh_post/'),
        ),
        migrations.AddField(
            model_name='neighborhoodpost',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neighborhoodpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighborhoodpost',
            name='description',
            field=models.TextField(),
        ),
    ]
