# Generated by Django 2.2.6 on 2019-10-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0024_auto_20191029_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhoodpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='neighborhoodpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='neighborhoodpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='neighborhoodpost',
            name='posted_on',
        ),
        migrations.RemoveField(
            model_name='neighborhoodpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='neighborhoodpost',
            name='user',
        ),
    ]
