# Generated by Django 2.2.6 on 2019-10-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0025_auto_20191029_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeighborhoodPost',
        ),
    ]
