# Generated by Django 2.2.6 on 2019-10-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0028_auto_20191029_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhoodpost',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='neighborhoodpost',
            name='posted_on',
        ),
    ]
