# Generated by Django 2.2.6 on 2019-10-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0029_auto_20191029_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeighborhoodPost',
        ),
    ]
