# Generated by Django 2.2.6 on 2019-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigh1', '0032_chatkeys_realchats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatkeys',
            name='chat_token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
