# Generated by Django 2.2.6 on 2019-10-29 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neigh1', '0033_auto_20191029_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatKeys',
            new_name='ChatKey',
        ),
        migrations.RenameModel(
            old_name='RealChats',
            new_name='RealChat',
        ),
    ]
